[project]
name = "driving_school"
authors = [
    { name = "Frappe", email = "developers@frappe.io"}
]
description = "Driving School Test Application"
requires-python = ">=3.10,<3.14"
readme = "README.md"
dynamic = ["version"]
dependencies = []

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "driving_school"
